language: node_js

node_js:
  - 10

branches:
  only:
    - master

before_script:
  - gem install dpl
  - npm install
  - npm run build-prod

script:
  - dpl --skip-cleanup --provider=heroku --app=tbilisi-traffic-routing-front --api-key=$HEROKU_API_KEY
